name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2.2.1

      - name: Run Biome
        run: biome ci --error-on-warnings .
