name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Biome
        uses: biomejs/setup-biome@fbd4c08f9a360b7c371d1688e00fbbffd68d103b # v2.0.0

      - name: Run Biome
        run: biome ci --error-on-warnings .
