name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2.2.1

      - name: Run Biome
        run: biome ci --error-on-warnings .
