name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Biome
        uses: biomejs/setup-biome@fcb95f3805d3a2fac0ca09635a90a9ac2b38188e # v2.4.0

      - name: Run Biome
        run: biome ci --error-on-warnings .
