name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Biome
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2.5.0

      - name: Run Biome
        run: biome ci --error-on-warnings .
