name: Biome

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  biome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Setup Biome
        uses: biomejs/setup-biome@b9af8bac86b0da736cfbfadbfeb3f7463da083f2 # v2.1.1

      - name: Run Biome
        run: biome ci --error-on-warnings .
